"""Compiled backend — compile TBPS to assembly for a CPU arch + board.

An *ahead-of-time* alternative to the bytecode interpreter: instead of emitting
8-byte interpreter slots run by the firmware, this emits CPU instructions that
perform each TBPS instruction's effect directly.

TBPS is **robot-agnostic**, so the backend is split into two layers it merely
orchestrates:

* **arch** (:class:`tbps_compiler.arch.Arch`) — the CPU instruction set and
  architectural facts (default :data:`~tbps_compiler.arch.MCS51`, the Intel
  8031/MCS-51). Owns control flow, the TIM ``djnz`` wait skeleton, scratch IRAM
  and the P1 input bits.
* **board** (:class:`tbps_compiler.board.Board`) — how a *specific* board/
  executor realizes the abstract intents (move axis, digital out). The default
  :data:`~tbps_compiler.board.ROB3` runs in hosted/subroutine mode, reusing the
  ROB3 firmware's RAM map + routines and mirroring ``prog_exec`` per
  instruction, so the compiled and interpreted runs leave the same state.

The generated assembly ``.include``s **tbps_isa.inc** (the TBPS language) plus
the arch's and board's own equate headers, so it uses SYMBOLIC equates rather
than magic literals. Assemble with those headers on the include path, e.g.
``sdas8051 -I <this package>/asm prog.asm``.
"""

from __future__ import annotations

import os

from . import parser as P
from .arch import Arch, DEFAULT_ARCH
from .board import Board, DEFAULT_BOARD
from .errors import CompileError
from .lexer import tokenize
from .parser import parse

# The TBPS language header (always included). Arch/board headers come from the
# selected layers' ``includes``.
ASM_DIR = os.path.join(os.path.dirname(__file__), "asm")
ISA_INC = os.path.join(ASM_DIR, "tbps_isa.inc")
ISA_INC_NAME = "tbps_isa.inc"


def _label(m: int) -> str:
    return f"Lmark_{m}"


def _emit_goto(node: P.Goto, out: list[str], counters: dict, arch: Arch) -> None:
    if node.count is None or node.count == 0:
        out.append(f"    ; GOTO {node.label}  (unconditional)")
        out.append(f"    ljmp {_label(node.label)}")
    else:
        cvar = arch.goto_counter(len(counters))
        counters[id(node)] = cvar
        out.append(f"    ; GOTO {node.label} . {node.count}  (loop)")
        out.append(f"    djnz 0x{cvar:02x},{_label(node.label)}")
        out.append(f"Lgoto_{node.line}:  ; fall through when loop exhausted")


def _emit_if(node: P.If, out: list[str], arch: Arch) -> None:
    bitaddr = arch.p1_bit(node.inp)
    if node.label is None:
        out.append(f"    ; IF {node.inp}  (wait until input low)")
        out.append(f"Lif_{node.line}:")
        out.append(f"    jb   0x{bitaddr:02x},Lif_{node.line}")   # high -> keep waiting
    else:
        out.append(f"    ; IF {node.inp} . {node.label}  (branch if low)")
        out.append(f"    jnb  0x{bitaddr:02x},{_label(node.label)}")  # low -> jump


def generate_asm(source: str, *, org: int = 0x2000, name: str = "tbps_prog",
                 include_isa: bool = True, arch: Arch = DEFAULT_ARCH,
                 board: Board = DEFAULT_BOARD) -> str:
    """Compile TBPS source to assembly for ``arch`` (CPU) + ``board`` (executor).

    The output ``.include``s ``tbps_isa.inc`` plus the arch/board equate headers
    unless ``include_isa=False``. Assemble with those headers on the include
    path, e.g. ``sdas8051 -I <this package>/asm prog.asm``.
    """
    lines = tokenize(source)
    parsed = parse(lines)
    if parsed.diagnostics:
        raise CompileError(parsed.diagnostics)

    includes = (ISA_INC_NAME, *arch.includes, *board.includes)

    out: list[str] = []
    out.append(f";;; {name} -- {arch.name} assembly from TBPS (board: {board.name})")
    out.append(";;; Generated by tbps_compiler.backend.")
    if board.banner:
        out.append(f";;; {board.banner}")
    out.append(f";;; Equates from: {', '.join(includes)}.")
    if include_isa:
        for inc in includes:
            out.append(f'    .include "{inc}"')
    out.append("    .area TBPS (ABS)")
    out.append(f"    .org 0x{org:04x}")
    out.append(f"{name}:")

    counters: dict = {}
    for node in parsed.nodes:
        if isinstance(node, P.ProgramStart):
            continue
        if isinstance(node, P.Mark):
            out.append(f"{_label(node.label)}:")
        elif isinstance(node, P.PosAxis):
            board.emit_pos(node, out)
        elif isinstance(node, P.PosStore):
            board.emit_pos_store(node, out)
        elif isinstance(node, P.Out):
            board.emit_out(node, out)
        elif isinstance(node, P.Tim):
            board.emit_tim_load(node, out)   # board loads the counter values
            arch.emit_tim_wait(node, out)    # arch spins the djnz down-counter
        elif isinstance(node, P.Goto):
            _emit_goto(node, out, counters, arch)
        elif isinstance(node, P.If):
            _emit_if(node, out, arch)
        elif isinstance(node, P.Nop):
            out.append("    nop")
        elif isinstance(node, (P.ProgramEnd, P.Halt)):
            out.append("    ; INS. / DEL.  (program end / halt)")
            out.append("    ret")
    out.append("    ret")
    out.append("")
    return "\n".join(out)
